/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.5/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
@file:Suppress("UnstableApiUsage")

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile


plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // id("com.gradle.plugin-publish") version "1.2.1"
    `kotlin-dsl`
    id("maven-publish")
}
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}

dependencies {
    implementation(libs.android.gradlePlugin)
    implementation(libs.android.tools.common)
    implementation(libs.firebase.crashlytics.gradlePlugin)
    implementation(libs.firebase.performance.gradlePlugin)
    implementation(libs.kotlin.gradlePlugin)
    implementation(libs.ksp.gradlePlugin)
    implementation(libs.room.gradlePlugin)
    implementation(libs.truth)
}

tasks {
    validatePlugins {
        enableStricterValidation = true
        failOnWarning = true
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    maven(url = "https://maven.aliyun.com/repository/gradle-plugin")
    maven(url = "https://maven.aliyun.com/repository/public")
    maven(url = "https://maven.aliyun.com/repository/central")
    maven(url = "https://maven.aliyun.com/repository/google")

    google()
    mavenCentral()
    gradlePluginPortal()
}

// The project version will be used as your plugin version when publishing.
version = "0.0.1-pre09"
group = "android.boot"
val remoteUrl = "${properties["gradle.publish.remoteurl"]}"
val mavenUserName = "${properties["gradle.publish.username"]}"
val mavenPwd = "${properties["gradle.publish.userpwd"]}"
println("remoteUrl:$remoteUrl\n credentials {\n   username = $mavenUserName \n   password = $mavenPwd \n  }")

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("boot") {
                from(components["kotlin"])
                groupId = "android.boot"
                artifactId = "plugin"
                version = version
            }
        }
        repositories {
            maven {
                setUrl(remoteUrl)
                credentials {
                    username = mavenUserName
                    password = mavenPwd
                }
            }
        }
    }
}

// Use java-gradle-plugin to generate plugin descriptors and specify both global and individual plugin properties.
// The names of the blocks inside "plugins" need to be unique, they will identify the plugins being configured.
// All properties are mandatory.
gradlePlugin {
    website.set("https://github.com/zhangwenxue/android-boot-plugin")
    vcsUrl.set("https://github.com/zhangwenxue/android-boot-plugin")
    plugins {
        /*create("androidBoot") {
            id = "android.boot.greeting"
            implementationClass = "android.boot.AndroidBootPlugin"
            displayName = "Gradle Greeting plugin"
            description = "Gradle plugin to say hello!"
        }*/
        create("androidApplicationCompose") {
            id = "android.boot.application.compose"
            implementationClass = "android.boot.plugin.AndroidApplicationComposeConventionPlugin"
        }

        create("androidApplication") {
            id = "android.boot.application"
            implementationClass = "android.boot.plugin.AndroidApplicationConventionPlugin"
        }
        create("androidApplicationJacoco") {
            id = "android.boot.application.jacoco"
            implementationClass = "android.boot.plugin.AndroidApplicationJacocoConventionPlugin"
        }
        create("androidLibraryCompose") {
            id = "android.boot.library.compose"
            implementationClass = "android.boot.plugin.AndroidLibraryComposeConventionPlugin"
        }
        create("androidLibrary") {
            id = "android.boot.library"
            implementationClass = "android.boot.plugin.AndroidLibraryConventionPlugin"
        }

        create("androidFeature") {
            id = "android.boot.feature"
            implementationClass = "plugin.AndroidFeatureConventionPlugin"
        }

        create("androidLibraryJacoco") {
            id = "android.boot.library.jacoco"
            implementationClass = "android.boot.plugin.AndroidLibraryJacocoConventionPlugin"
        }

        create("androidTest") {
            id = "android.boot.test"
            implementationClass = "android.boot.plugin.AndroidTestConventionPlugin"
        }

        create("androidHilt") {
            id = "android.boot.hilt"
            implementationClass = "android.boot.plugin.AndroidHiltConventionPlugin"
        }

        create("androidRoom") {
            id = "android.boot.room"
            implementationClass = "android.boot.plugin.AndroidRoomConventionPlugin"
        }

        create("androidLint") {
            id = "android.boot.lint"
            implementationClass = "android.boot.plugin.AndroidLintConventionPlugin"
        }
        create("jvmLibrary") {
            id = "android.boot.jvm.library"
            implementationClass = "android.boot.plugin.JvmLibraryConventionPlugin"
        }
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("1.9.20")
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("1.9.20")

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) }
                }
            }
        }
    }
}


gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}
